import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

// Configure global font variables used across the entire app.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Optional monospace font variable (available for code-like text styles).
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata controls browser tab title and SEO description for all pages.
export const metadata: Metadata = {
  title: "Rohit Tapader|PM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Root HTML shell shared by every route (e.g., /, /api routes are separate).
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Page-level content gets injected here by Next.js. */}
        {children}
        {/* Vercel Analytics script runs globally for traffic insights. */}
        <Analytics />
      </body>
    </html>
  );
}
